all: remove staticcheck warnings
auth/auth.go:65:1: comment on exported function FromEnvironment should be of the form "FromEnvironment ..." (ST1020)
auth/auth.go:132:1: comment on exported function FromEndPoint should be of the form "FromEndPoint ..." (ST1020)
auth/auth.go:142:1: comment on exported function FromFile should be of the form "FromFile ..." (ST1020)
cmd/snellerd/badrequest_test.go:73:6: type emptyEnv is unused (U1000)
cmd/snellerd/badrequest_test.go:75:19: func emptyEnv.CacheValues is unused (U1000)
cmd/snellerd/badrequest_test.go:79:6: type noTableHandle is unused (U1000)
cmd/snellerd/badrequest_test.go:81:24: func noTableHandle.Encode is unused (U1000)
cmd/snellerd/badrequest_test.go:86:24: func noTableHandle.Open is unused (U1000)
cmd/snellerd/badrequest_test.go:91:19: func emptyEnv.Stat is unused (U1000)
cmd/snellerd/run_worker.go:128:21: methods on the same type should have the same receiver name (seen 1x "e", 3x "t") (ST1016)
date/time.go:96:1: comment on exported function Unix should be of the form "Unix ..." (ST1020)
date/time.go:156:1: comment on exported method UnixMicro should be of the form "UnixMicro ..." (ST1020)
date/time.go:162:1: comment on exported method UnixNano should be of the form "UnixNano ..." (ST1020)
date/time.go:178:1: comment on exported method After should be of the form "After ..." (ST1020)
db/def.go:60:6: func drop is unused (U1000)
expr/blob/blob.go:386:24: methods on the same type should have the same receiver name (seen 1x "be", 2x "b") (ST1016)
expr/check.go:296:6: type visitfn is unused (U1000)
expr/check.go:298:18: func visitfn.Visit is unused (U1000)
expr/check.go:302:6: func containsAggregate is unused (U1000)
generate.go:15:1: at least one file in a package should have a package comment (ST1000)
heap/heap.go:15:1: package comment should be of the form "Package heap ..." (ST1000)
internal/stringext/stringUtils.go:15:1: at least one file in a package should have a package comment (ST1000)
ion/compress.go:27:2: const maxInterned is unused (U1000)
jsonrl/state.go:231:5: error var end should have name of the form errFoo (ST1012)
jsonrl/state.go:233:6: func hintsFromJson should be hintsFromJSON (ST1003)
plan/apply.go:21:6: func gensym is unused (U1000)
plan/lower.go:390:6: func autoname is unused (U1000)
plan/output.go:286:22: methods on the same type should have the same receiver name (seen 1x "i", 2x "is") (ST1016)
regexp2/DsLarge.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/DsLarge.go:48:9: range var nodeId should be nodeID (ST1003)
regexp2/DsLarge.go:86:6: func nodeIdForDs should be nodeIDForDs (ST1003)
regexp2/DsTiny.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/DsTiny.go:194:18: func (*DsTiny).findCharGroup is unused (U1000)
regexp2/Graphviz.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/Regexp2.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/Regexp2.go:159:4: var nodeId should be nodeID (ST1003)
regexp2/Regexp2.go:224:18: error strings should not end with punctuation or newlines (ST1005)
regexp2/TestTools.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/autom.CharGroups.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/autom.DfaMin.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/autom.DfaMin.go:124:9: range var nodeId should be nodeID (ST1003)
regexp2/autom.Edge.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/autom.Nfa2Dfa.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/autom.Nfa2Dfa.go:53:9: range var nodeId should be nodeID (ST1003)
regexp2/autom.Nfa2Dfa.go:110:6: range var nodeId should be nodeID (ST1003)
regexp2/autom.NodeDfa.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/autom.NodeDfa.go:48:15: func (*DFA).removeEdge is unused (U1000)
regexp2/autom.NodeDfa.go:136:28: method parameter nodeId should be nodeID (ST1003)
regexp2/autom.NodeDfa.go:145:7: range var nodeId should be nodeID (ST1003)
regexp2/autom.NodeDfa.go:159:5: var startId should be startID (ST1003)
regexp2/autom.NodeDfa.go:164:7: range var nodeId should be nodeID (ST1003)
regexp2/autom.NodeDfa.go:179:47: method parameter nodeId should be nodeID (ST1003)
regexp2/autom.NodeDfa.go:191:2: var startId should be startID (ST1003)
regexp2/autom.NodeDfa.go:205:7: range var nodeId should be nodeID (ST1003)
regexp2/autom.NodeDfa.go:315:10: range var oldId should be oldID (ST1003)
regexp2/autom.NodeDfa.go:324:8: range var oldId should be oldID (ST1003)
regexp2/autom.NodeDfa.go:325:5: var newId should be newID (ST1003)
regexp2/autom.NodeNfa.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/autom.NodeNfa.go:26:2: field key is unused (U1000)
regexp2/autom.NodeNfa.go:61:2: struct field startIdRLZ should be startIDRLZ (ST1003)
regexp2/autom.NodeNfa.go:103:28: method parameter nodeId should be nodeID (ST1003)
regexp2/autom.NodeNfa.go:112:7: range var nodeId should be nodeID (ST1003)
regexp2/autom.NodeNfa.go:126:5: var startId should be startID (ST1003)
regexp2/autom.NodeNfa.go:131:7: range var nodeId should be nodeID (ST1003)
regexp2/autom.NodeNfa.go:142:24: func (*NFAStore).numberOfStates is unused (U1000)
regexp2/autom.NodeNfa.go:146:24: func (*NFAStore).reachableNodesTraverse is unused (U1000)
regexp2/autom.NodeNfa.go:146:47: method parameter nodeId should be nodeID (ST1003)
regexp2/autom.NodeNfa.go:163:24: func (*NFAStore).reachableNodes is unused (U1000)
regexp2/autom.NodeNfa.go:164:5: var startId should be startID (ST1003)
regexp2/autom.NodeNfa.go:174:24: func (*NFAStore).removeNonReachableNodes is unused (U1000)
regexp2/autom.NodeNfa.go:179:7: range var nodeId should be nodeID (ST1003)
regexp2/autom.NodeNfa.go:302:7: range var nodeId should be nodeID (ST1003)
regexp2/autom.NodeNfa.go:318:8: range var nodeId should be nodeID (ST1003)
regexp2/autom.Types.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/lib.Map.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/lib.Map.go:26:22: func (*mapT[K, V]).empty is unused (U1000)
regexp2/lib.Map.go:58:22: func (*mapT[K, V]).containsValue is unused (U1000)
regexp2/lib.Set.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/lib.Vector.go:15:1: at least one file in a package should have a package comment (ST1000)
regexp2/symbolRange.go:15:1: at least one file in a package should have a package comment (ST1000)
sorting/doc.go:15:1: package comment should be of the form "Package sorting ..." (ST1000)
vm/asm_utils.go:39:5: var opcodeToIdMapOnce should be opcodeToIDMapOnce (ST1003)
vm/asm_utils.go:40:5: var opcodeToIdMap should be opcodeToIDMap (ST1003)
vm/bclayout.go:44:22: func (*vRegLayout).items is unused (U1000)
vm/find.go:17:20: func (*bytecode).find is unused (U1000)
vm/limit.go:38:1: comment on exported function NewLimit should be of the form "NewLimit ..." (ST1020)
vm/ssa.go:2598:10: empty branch (SA9003)